name: 🐛 Bug Report
description: Report a bug with a skill, the installer, or the repository
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🏰 Rei Skills — Bug Report
        Help us improve the collection by reporting issues!

  - type: input
    id: skill-name
    attributes:
      label: Affected Skill or Component
      placeholder: "e.g., docker-expert, installer, validation"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in detail
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      value: |
        1.
        2.
        3.

  - type: dropdown
    id: platform
    attributes:
      label: AI Tool
      options:
        - Claude Code
        - Gemini CLI
        - Cursor
        - Codex CLI
        - Antigravity
        - OpenCode
        - Other

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 14.3, Ubuntu 22.04, Windows 11"
