name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🏰 Rei Skills — Feature Request
        We'd love to hear your ideas!

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this help you?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Critical
